{% set version = "1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tmvtnorm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmvtnorm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmvtnorm/tmvtnorm_{{ version }}.tar.gz
  sha256: 2d9b2c5330d11a62384b4c0c1c012be34806b48683898045a4a40fdb9a8e1bba

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-mvtnorm                  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-gmm                      # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-gmm
    - r-mvtnorm
  run:
    - r-base
    - r-matrix
    - r-gmm
    - r-mvtnorm

test:
  commands:
    - $R -e "library('tmvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('tmvtnorm')\""  # [win]

about:
  home: http://www.r-project.org
  license: GPL-2.0-or-later
  summary: Random number generation for the truncated multivariate normal and Student t distribution.  Computes probabilities, quantiles and densities,  including one-dimensional and bivariate marginal densities. Computes first and second moments (i.e. mean and covariance matrix) for the double-truncated multinormal case.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
