{% set version = "1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tmvtnorm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tmvtnorm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tmvtnorm/tmvtnorm_{{ version }}.tar.gz
  sha256: 1c7a606bdce4319a6fdb4180fef499c293df3412d8583e296869521ece5460fe

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-gmm
    - r-mvtnorm
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-gmm
    - r-mvtnorm

test:
  commands:
    - $R -e "library('tmvtnorm')"           # [not win]
    - "\"%R%\" -e \"library('tmvtnorm')\""  # [win]

about:
  home: http://www.r-project.org
  license: GPL-2.0-or-later
  summary: Random number generation for the truncated multivariate normal and Student t distribution.  Computes probabilities, quantiles and densities,  including one-dimensional and bivariate marginal densities. Computes first and second moments (i.e. mean and covariance matrix) for the double-truncated multinormal case.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
