appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: gDupEVnZ5QtcgkWpXu6T+aAAxiBai3E+ZY114eHc2lF4QhBcfdDopjb5pYytu58ktMf6wsKXKs206527RgasiHKu4tJeYio3TOxxOPqcogX03aOz4rfO2P/5LjVfjWtjMk4UwaQSxsWDiubG5kHMBQkMJpjiGeVIRta+qLhiJI1l/hMk6XTh/ycwzly02VXoKukYV8hpMPbOh8VVZRFnQIJYh3RO2Zd2v3lwi/peWtdYLWQhXI+fwzPu1lf20ysHWtM2wI0Of5Tg7Dj+FLeleJOVh6od07FCAr5sTSmh1K3IByetR2QAYm6+3smMZq/L608/NC7D7HPDqfXrKIWlKwO97L0yJDQJtO4GKozixao9aRaAAMIuYEl5wB06X6uGndIU0gEd5sLZMWatWZFFxYZSvqk1CadYQbxbmGa6ouX9X7jeuukqIB/PGxsNQyunPCniULc/NmQOoPzI93XOEzVr/A1Fwh2dTtIOt0d4MAam0PC7DZwi9JxVERp5feZE+Lj1b0bPSNnzxcB15o2I+/Gp5LJpm+0MwSOlVS/bNrMJIJ4HUoiUpApO5vD6VLk+ujJNzsUKBlu+hTfMhZpWVSUriF2Hn7K5FDp4RUjlX8v770C+JLK++jxETx+ryI/p5dcewgjZFrW2AQBCSoFC2q7bJXLDG+xdCRlo4RDc2T4=
